[package]
name = "bacak-remote-server"
edition.workspace = true
version.workspace = true
license.workspace = true

[[bin]]
name = "bacak-remote-server"
path = "src/main.rs"

[dependencies]
bacak-remote-proto = { path = "../bacak-remote-proto" }
tokio = { version = "1", features = ["rt-multi-thread", "net", "macros", "time", "sync"] }
scrap = "0.5"
zstd = "0.13"
enigo = "0.2"
anyhow = "1"
thiserror = "2"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
clap = { version = "4", features = ["derive"] }
