//! "Uzak Masaüstü" (Remote Desktop) panel — pairs with a `bacak-remote-server`
//! (see `../../../uzakel/uzakel-pc`) and displays its PC screen inside the
//! real Bacak OS desktop, forwarding local pointer input back to it. This is
//! the plugin `bacak-remote-client`'s own `render.rs` module doc names as
//! its intended home, instead of a standalone `winit` window — see that
//! crate's README for the two real bugs the standalone version's Wayland
//! testing found before this integration existed.
//!
//! ## Why a cross-workspace dependency instead of reimplementing the protocol
//!
//! `bacak-remote-proto` (PIN + ephemeral X25519 ECDH + HKDF-SHA256 +
//! ChaCha20-Poly1305, verified on real Windows/Linux hardware — see that
//! workspace's README) is pulled in as-is via a path dependency
//! (`../../../uzakel/uzakel-pc/bacak-remote-proto`). Reimplementing the same
//! handshake a second time here would be a second place to get the crypto
//! subtly wrong; a path dependency costs nothing at runtime and keeps the
//! two projects' wire formats identical by construction.
//!
//! ## What's duplicated anyway, and why
//!
//! `bacak-remote-client`'s own frame-reassembly (`decode.rs`) is small,
//! pure, and tangled up with that crate's `winit`/`wgpu` types — copying its
//! ~40 lines here (below) is simpler and lower-risk than extracting a shared
//! library crate just for this one struct. The pairing/receive network loop
//! (`run`, below) mirrors that crate's `network.rs` for the same reason:
//! this compositor is Smithay/calloop-driven, not `winit`, so the two loops
//! can't literally share code without a much larger refactor than this
//! feature warrants.
//!
//! ## v1 limitation: config-file address, not a text-entry dialog
//!
//! Typing an IP on the real desktop needs an on-screen-keyboard-driven text
//! field — real UI machinery this panel doesn't build yet. For now the
//! target server's address is read from `~/.config/bacak-remote/pair.json`
//! (`{"ip": "..."}`), written by hand for now; the panel just shows a clear
//! status message if it's missing or invalid rather than failing silently.
//!
//! ## Who generates the pairing PIN
//!
//! The PIN is generated *here*, on the BacakOS side, the moment the panel
//! opens, and shown large on screen (see `render_remote_desktop_panel`) —
//! not read from config and not generated by `bacak-remote-server`. This is
//! the reverse of that crate's own standalone-client story: typing a PIN on
//! BacakOS (no physical keyboard) is exactly the friction the "v1
//! limitation" above describes, while the person at the PC being viewed has
//! a normal keyboard right there. So the operator reads the PIN off the
//! BacakOS screen and types it into `bacak-remote-server`'s console prompt,
//! which then validates the `PairRequest` it receives against that typed
//! value — see that binary's `main.rs`.

use std::net::{IpAddr, SocketAddr, UdpSocket as StdUdpSocket};
use std::sync::mpsc;
use std::sync::{Arc, Mutex as StdMutex};

use bacak_remote_proto::crypto::{generate_pin, Cipher, EphemeralKeypair, Opener};
use bacak_remote_proto::{
    decode, encode, open_message, seal_message, Codec, FrameInfo, InputEvent, Message, DEFAULT_INPUT_PORT, DEFAULT_VIDEO_PORT,
};
use serde::Deserialize;
use smithay::backend::allocator::Fourcc;
use smithay::backend::renderer::element::memory::MemoryRenderBuffer;
use smithay::utils::Transform;

use crate::state::{BacakState, LABEL_SUPERSAMPLE};
use crate::text::TextRenderer;
use crate::wm::{OutputId, Rect};

fn rasterize(text: Option<&TextRenderer>, s: &str, px: f32, color: [u8; 3], max_w: usize) -> Option<(MemoryRenderBuffer, usize, usize)> {
    let ss = LABEL_SUPERSAMPLE;
    let (rgba, w, h) = text?.rasterize_line(s, px * ss as f32, color, max_w * ss as usize)?;
    let buf = MemoryRenderBuffer::from_slice(&rgba, Fourcc::Abgr8888, (w as i32, h as i32), ss, Transform::Normal, None);
    Some((buf, w / ss as usize, h / ss as usize))
}

#[derive(Deserialize)]
struct PairConfig {
    ip: IpAddr,
    #[serde(default = "default_video_port")]
    video_port: u16,
    #[serde(default = "default_input_port")]
    input_port: u16,
}
fn default_video_port() -> u16 {
    DEFAULT_VIDEO_PORT
}
fn default_input_port() -> u16 {
    DEFAULT_INPUT_PORT
}

fn pair_config_path() -> std::path::PathBuf {
    let home = std::env::var("HOME").unwrap_or_else(|_| "/root".to_string());
    std::path::PathBuf::from(home).join(".config/bacak-remote/pair.json")
}

fn read_pair_config() -> Result<PairConfig, String> {
    let path = pair_config_path();
    let raw = std::fs::read_to_string(&path).map_err(|_| format!("{} bulunamadı", path.display()))?;
    serde_json::from_str(&raw).map_err(|e| format!("geçersiz pair.json: {e}"))
}

struct DecodedFrame {
    width: u32,
    height: u32,
    bgra: Vec<u8>,
}

/// One in-flight frame's chunks, reassembled the same "drop the incomplete
/// frame the moment a newer one starts" way as
/// `uzakel-pc/bacak-remote-client/src/decode.rs::FrameReassembler` — see
/// that file's doc comment for why (a live desktop stream prefers a dropped
/// frame over a stale one).
#[derive(Default)]
struct FrameReassembler {
    current: Option<InProgress>,
}
struct InProgress {
    info: FrameInfo,
    chunks: Vec<Option<Vec<u8>>>,
    received: u16,
}
impl FrameReassembler {
    fn start_frame(&mut self, info: FrameInfo) {
        self.current = Some(InProgress { chunks: vec![None; info.chunk_count as usize], received: 0, info });
    }

    fn add_chunk(&mut self, frame_id: u32, chunk_index: u16, data: Vec<u8>) -> Option<DecodedFrame> {
        let progress = self.current.as_mut()?;
        if progress.info.frame_id != frame_id {
            return None;
        }
        let slot = progress.chunks.get_mut(chunk_index as usize)?;
        if slot.is_none() {
            *slot = Some(data);
            progress.received += 1;
        }
        if progress.received < progress.info.chunk_count {
            return None;
        }
        let progress = self.current.take()?;
        let mut payload = Vec::with_capacity(progress.info.payload_len as usize);
        for chunk in progress.chunks {
            payload.extend_from_slice(&chunk?);
        }
        let bgra = match progress.info.codec {
            Codec::RawZstd => zstd::stream::decode_all(payload.as_slice()).ok()?,
        };
        Some(DecodedFrame { width: progress.info.width, height: progress.info.height, bgra })
    }
}

enum SessionStatus {
    Connecting,
    Failed(String),
    Connected { width: u32, height: u32 },
}

/// Owns the background pairing/receive thread and the encrypted input send
/// path. Dropping this stops the thread on its next socket timeout/error
/// (no explicit shutdown signal — matches the standalone client's
/// fire-and-forget teardown, acceptable since a session is one-per-panel and
/// short-lived).
struct RemoteDesktopSession {
    frame_rx: mpsc::Receiver<DecodedFrame>,
    status_rx: mpsc::Receiver<SessionStatus>,
    status: SessionStatus,
    input_socket: StdUdpSocket,
    input_cipher: Arc<StdMutex<Option<Cipher>>>,
}

impl RemoteDesktopSession {
    /// `pin` is generated by the caller (`open_remote_desktop_panel`), not
    /// read from `cfg` — see the module doc's "Who generates the pairing
    /// PIN" section.
    fn start(cfg: PairConfig, pin: u32) -> anyhow::Result<Self> {
        let (frame_tx, frame_rx) = mpsc::channel();
        let (status_tx, status_rx) = mpsc::channel();
        let input_cipher = Arc::new(StdMutex::new(None));

        let input_socket = StdUdpSocket::bind("0.0.0.0:0")?;
        input_socket.connect(SocketAddr::new(cfg.ip, cfg.input_port))?;
        input_socket.set_nonblocking(true)?;

        let thread_cipher = input_cipher.clone();
        let thread_status_tx = status_tx.clone();
        std::thread::Builder::new().name("bacak-remote-desktop-net".into()).spawn(move || {
            let runtime = match tokio::runtime::Runtime::new() {
                Ok(rt) => rt,
                Err(e) => {
                    let _ = thread_status_tx.send(SessionStatus::Failed(format!("tokio runtime: {e}")));
                    return;
                }
            };
            if let Err(e) = runtime.block_on(run(cfg, pin, frame_tx, thread_status_tx.clone(), thread_cipher)) {
                let _ = thread_status_tx.send(SessionStatus::Failed(e.to_string()));
            }
        })?;

        Ok(Self { frame_rx, status_rx, status: SessionStatus::Connecting, input_socket, input_cipher })
    }

    /// Drains pending status updates and returns the newest decoded frame,
    /// if any arrived since the last call (older queued frames are dropped —
    /// same "freshest wins" policy as the reassembler above).
    fn poll(&mut self) -> Option<(u32, u32, Vec<u8>)> {
        while let Ok(s) = self.status_rx.try_recv() {
            self.status = s;
        }
        let mut latest = None;
        while let Ok(f) = self.frame_rx.try_recv() {
            latest = Some((f.width, f.height, f.bgra));
        }
        latest
    }

    fn send_input(&self, event: InputEvent) {
        let mut guard = self.input_cipher.lock().unwrap();
        let Some(cipher) = guard.as_mut() else { return };
        let Ok(sealed) = seal_message(&Message::Input(event), cipher) else { return };
        if let Ok(bytes) = encode(&sealed) {
            let _ = self.input_socket.send(&bytes);
        }
    }
}

async fn run(
    cfg: PairConfig,
    pin: u32,
    frame_tx: mpsc::Sender<DecodedFrame>,
    status_tx: mpsc::Sender<SessionStatus>,
    input_cipher: Arc<StdMutex<Option<Cipher>>>,
) -> anyhow::Result<()> {
    let socket = tokio::net::UdpSocket::bind("0.0.0.0:0").await?;
    socket.connect(SocketAddr::new(cfg.ip, cfg.video_port)).await?;

    let client_keypair = EphemeralKeypair::generate();
    let client_pubkey = client_keypair.public_bytes;
    let pair_request = encode(&Message::PairRequest { client_name: "bacak-os".into(), pin, client_pubkey })?;

    let (server_pubkey, confirm_tag, (width, height)) = loop {
        socket.send(&pair_request).await?;
        let mut buf = [0u8; 512];
        if let Ok(Ok(len)) = tokio::time::timeout(std::time::Duration::from_millis(500), socket.recv(&mut buf)).await {
            match decode(&buf[..len]) {
                Ok(Message::PairResponse { accepted: true, server_pubkey, confirm_tag, screen_width, screen_height }) => {
                    break (server_pubkey, confirm_tag, (screen_width, screen_height));
                }
                Ok(Message::PairResponse { accepted: false, .. }) => anyhow::bail!("sunucu PIN'i reddetti"),
                _ => {}
            }
        }
    };

    let material = client_keypair.derive(server_pubkey, pin, client_pubkey, server_pubkey);
    if material.confirm_tag != confirm_tag {
        anyhow::bail!("eşleşme doğrulaması başarısız — yanlış PIN ya da güvenilmeyen bağlantı");
    }
    let video_keys = material.channel_keys("video");
    let input_keys = material.channel_keys("input");
    let mut video_opener = Opener::new(video_keys.s2c_key);
    *input_cipher.lock().unwrap() = Some(Cipher::new(input_keys.c2s_key));

    let _ = status_tx.send(SessionStatus::Connected { width, height });

    let mut reassembler = FrameReassembler::default();
    let mut buf = vec![0u8; 2048];
    loop {
        let len = socket.recv(&mut buf).await?;
        let Ok(msg) = decode(&buf[..len]) else { continue };
        let Ok(inner) = open_message(&msg, &mut video_opener) else { continue };
        match inner {
            Message::FrameInfo(info) => reassembler.start_frame(info),
            Message::FrameChunk(chunk) => {
                if let Some(frame) = reassembler.add_chunk(chunk.frame_id, chunk.chunk_index, chunk.data) {
                    if frame_tx.send(frame).is_err() {
                        return Ok(()); // panel closed
                    }
                }
            }
            _ => {}
        }
    }
}

/// The "Uzak Masaüstü" panel's live state — opened from the Control Center's
/// tile (see `plugins/control_center.rs`'s `CcAction::RemoteDesktopConnect`).
pub struct RemoteDesktopPanel {
    output: OutputId,
    /// Where the video frame is blitted (fills most of the output — this is
    /// meant to be looked at, unlike the small utility panels).
    video_rect: Rect,
    close_rect: Rect,
    close_label: Option<(MemoryRenderBuffer, usize, usize)>,
    status_label: Option<(MemoryRenderBuffer, usize, usize)>,
    /// Large "PIN: 123456" label, generated once when the panel opens (see
    /// the module doc's "Who generates the pairing PIN") and shown until the
    /// session connects — the operator at the shared PC reads this off the
    /// BacakOS screen and types it into `bacak-remote-server`'s prompt.
    pin_label: Option<(MemoryRenderBuffer, usize, usize)>,
    session: RemoteDesktopSession,
    /// The most recently decoded frame, already wrapped as a render buffer —
    /// rebuilt (not mutated in place) each time a new frame arrives, since
    /// `MemoryRenderBuffer` has no in-place "replace the pixels" API here.
    frame: Option<(MemoryRenderBuffer, u32, u32)>,
    /// Slot that owns the current drag — a real libinput touch slot (always
    /// >= 0), or [`MOUSE_SLOT`] for a mouse/pointer-driven drag. Mouse and
    /// touch share this one field (and the same `TouchDown`/`TouchMotion`/
    /// `TouchUp` wire messages below) so the two input paths can't drift
    /// apart the way they did when the mouse path used its own relative-
    /// motion model — see the module doc. `None` when nothing is down.
    touch_slot: Option<i32>,
}

/// Sentinel slot for a mouse/pointer-driven drag on the panel, routed
/// through the same absolute-position `TouchDown`/`TouchMotion`/`TouchUp`
/// machinery real touch slots use. Real libinput touch slots are always
/// `>= 0`, so a negative sentinel can never collide with one.
const MOUSE_SLOT: i32 = -1;

impl BacakState {
    fn remote_desktop_status_text(status: &SessionStatus) -> String {
        match status {
            SessionStatus::Connecting => "Bağlanıyor…".to_string(),
            SessionStatus::Failed(e) => format!("Bağlantı hatası: {e}"),
            SessionStatus::Connected { width, height } => format!("Bağlandı — {width}x{height}"),
        }
    }

    /// Open the Remote Desktop panel: reads `~/.config/bacak-remote/pair.json`
    /// and starts pairing immediately. On a missing/invalid config, still
    /// opens the panel so the person sees *why* it can't connect instead of
    /// nothing happening when they tap the tile.
    pub fn open_remote_desktop_panel(&mut self, out: OutputId) {
        self.control_center = None;

        // Full-bleed: the remote screen is the content people actually want
        // to look at, so it covers the *entire* output — no margin — with
        // the close button and status line floating as a small overlay on
        // top of it (see `render_remote_desktop_panel`) rather than reserving
        // dedicated space that would shrink the video.
        let bounds = self.wm.output(out).map(|o| o.bounds).unwrap_or(Rect::new(0.0, 0.0, 1920.0, 1080.0));
        let video_rect = bounds;
        let m = 16.0;
        // Bottom-right, alongside the status line (bottom-left) — a single
        // overlay strip along the bottom edge rather than splitting the
        // controls between the top and bottom of the screen.
        let close_rect = Rect::new(bounds.x + bounds.w - m - 100.0, bounds.y + bounds.h - m - 36.0, 100.0, 36.0);

        let text = self.text.as_ref();
        const LABEL: [u8; 3] = [232, 236, 244];
        let close_label = rasterize(text, "Kapat", 14.0, LABEL, 100);

        // Generated here, not read from config — see the module doc's "Who
        // generates the pairing PIN". Shown large below so the operator at
        // the shared PC can read it off this screen and type it into
        // `bacak-remote-server`'s console prompt.
        let pin = generate_pin();
        let pin_label = rasterize(text, &format!("PIN: {pin:06}"), 40.0, LABEL, (video_rect.w as usize).max(200));

        let outcome = read_pair_config().and_then(|cfg| RemoteDesktopSession::start(cfg, pin).map_err(|e| e.to_string()));
        let (session, status_text) = match outcome {
            Ok(session) => {
                let text = Self::remote_desktop_status_text(&session.status);
                (session, text)
            }
            Err(e) => {
                // No server to talk to — a session that immediately reports
                // Failed, so the render/close path stays uniform (always a
                // session, never an Option<Option<..>>).
                let (tx, rx) = mpsc::channel();
                let (stx, srx) = mpsc::channel();
                let _ = stx.send(SessionStatus::Failed(e.clone()));
                drop(tx);
                let dummy_socket = StdUdpSocket::bind("0.0.0.0:0").expect("bind ephemeral UDP socket");
                let session = RemoteDesktopSession {
                    frame_rx: rx,
                    status_rx: srx,
                    status: SessionStatus::Failed(e.clone()),
                    input_socket: dummy_socket,
                    input_cipher: Arc::new(StdMutex::new(None)),
                };
                (session, Self::remote_desktop_status_text(&SessionStatus::Failed(e)))
            }
        };
        let status_label = rasterize(text, &status_text, 14.0, LABEL, video_rect.w as usize);

        self.remote_desktop_panel = Some(RemoteDesktopPanel {
            output: out,
            video_rect,
            close_rect,
            close_label,
            status_label,
            pin_label,
            session,
            frame: None,
            touch_slot: None,
        });
    }

    pub fn close_remote_desktop_panel(&mut self) {
        self.remote_desktop_panel = None;
    }

    /// Poll the active session for a new frame / status change, updating the
    /// panel's texture and status label. Returns `true` if a redraw is
    /// warranted (called from the plugin's `tick`).
    pub fn remote_desktop_tick(&mut self) -> bool {
        let Some(panel) = self.remote_desktop_panel.as_mut() else { return false };
        let mut dirty = false;
        if let Some((w, h, bgra)) = panel.session.poll() {
            let buf = MemoryRenderBuffer::from_slice(&bgra, Fourcc::Argb8888, (w as i32, h as i32), 1, Transform::Normal, None);
            panel.frame = Some((buf, w, h));
            dirty = true;
        }
        let status_text = Self::remote_desktop_status_text(&panel.session.status);
        let text = self.text.as_ref();
        panel.status_label = rasterize(text, &status_text, 14.0, [232, 236, 244], panel.video_rect.w as usize);
        dirty
    }

    /// A mouse press while the panel is open, routed through the same
    /// absolute-position machinery [`Self::remote_desktop_touch_press`] uses
    /// (with [`MOUSE_SLOT`] standing in for a touch slot) — a mouse click
    /// and a finger tap land in the same place on the remote screen instead
    /// of the mouse nudging a separate relative cursor. See the module doc.
    pub fn remote_desktop_press(&mut self, px: f32, py: f32) -> bool {
        self.remote_desktop_touch_press(px, py, MOUSE_SLOT)
    }

    /// Mouse-drag continuation — only while the mouse (not a finger) owns
    /// the current drag, so the two input paths can't fight over one panel.
    pub fn remote_desktop_pointer_motion(&mut self, px: f32, py: f32) -> bool {
        if self.remote_desktop_touch_slot() != Some(MOUSE_SLOT) {
            return false;
        }
        self.remote_desktop_touch_motion(px, py)
    }

    pub fn remote_desktop_pointer_release(&mut self, _px: f32, _py: f32) -> bool {
        if self.remote_desktop_touch_slot() != Some(MOUSE_SLOT) {
            return false;
        }
        self.remote_desktop_touch_up()
    }

    /// Whether touch `slot` (or [`MOUSE_SLOT`] for the mouse) currently owns
    /// [`Self::remote_desktop_touch_press`]).
    pub fn remote_desktop_touch_slot(&self) -> Option<i32> {
        self.remote_desktop_panel.as_ref().and_then(|p| p.touch_slot)
    }

    /// Touch-down on the panel (also reached from [`Self::remote_desktop_press`]
    /// with [`MOUSE_SLOT`]): sends the protocol's absolute `TouchDown { x, y }`
    /// — a tap (or click) is expected to land exactly where it happened, not
    /// wherever a shared relative cursor was last left. `finger_id` doubles
    /// as the owning slot so a second concurrent finger (if one ever reaches
    /// here) doesn't fight this one for the remote pointer — see
    /// `input_inject.rs`'s `active_finger` on the server side.
    pub fn remote_desktop_touch_press(&mut self, tx: f32, ty: f32, slot: i32) -> bool {
        let Some(panel) = self.remote_desktop_panel.as_mut() else { return false };
        if panel.close_rect.contains(tx, ty) {
            self.remote_desktop_panel = None;
            return true;
        }
        if panel.video_rect.contains(tx, ty) {
            // A drag already in progress (mouse or another finger) keeps
            // ownership — swallow the extra press rather than letting it
            // steal `touch_slot` out from under the first one, which would
            // strand its eventual up/release with nothing to settle and
            // leave the remote button/finger stuck down.
            if panel.touch_slot.is_some_and(|owner| owner != slot) {
                return true;
            }
            let (nx, ny) = norm_in_rect(panel.video_rect, tx, ty);
            panel.touch_slot = Some(slot);
            panel.session.send_input(InputEvent::TouchDown { finger_id: slot as u32, x: nx, y: ny });
            return true;
        }
        // Any other press outside the panel closes it, matching the Uzakel
        // QR panel's "any tap dismisses" convention for a modal-ish overlay.
        self.remote_desktop_panel = None;
        true
    }

    /// Touch-drag continuation: like the down, sends the finger's new
    /// *absolute* normalized position rather than a delta.
    pub fn remote_desktop_touch_motion(&mut self, tx: f32, ty: f32) -> bool {
        let Some(panel) = self.remote_desktop_panel.as_mut() else { return false };
        let Some(slot) = panel.touch_slot else { return false };
        if !panel.video_rect.contains(tx, ty) {
            return false;
        }
        let (nx, ny) = norm_in_rect(panel.video_rect, tx, ty);
        panel.session.send_input(InputEvent::TouchMotion { finger_id: slot as u32, x: nx, y: ny });
        true
    }

    /// Touch equivalent of [`Self::remote_desktop_pointer_release`]. Unlike
    /// the pointer path, `on_touch_up` carries no coordinates — but that's
    /// fine here since `TouchUp` only needs the finger id, which the claimed
    /// slot already gives us.
    pub fn remote_desktop_touch_up(&mut self) -> bool {
        let Some(panel) = self.remote_desktop_panel.as_mut() else { return false };
        let Some(slot) = panel.touch_slot.take() else { return false };
        panel.session.send_input(InputEvent::TouchUp { finger_id: slot as u32 });
        true
    }
}

/// `(x, y)` global coords → 0.0..=1.0 normalized position within `rect`,
/// clamped so a pointer at the very edge still maps inside 0.0..=1.0.
fn norm_in_rect(rect: Rect, x: f32, y: f32) -> (f32, f32) {
    let nx = ((x - rect.x) / rect.w.max(1.0)).clamp(0.0, 1.0);
    let ny = ((y - rect.y) / rect.h.max(1.0)).clamp(0.0, 1.0);
    (nx, ny)
}

pub(crate) fn render_remote_desktop_panel(
    state: &BacakState,
    renderer: &mut smithay::backend::renderer::gles::GlesRenderer,
    output: OutputId,
    output_scale: i32,
    off_x: i32,
    off_y: i32,
    out: &mut Vec<crate::render::BacakElements>,
) {
    use smithay::backend::renderer::element::memory::MemoryRenderBufferRenderElement;
    use smithay::backend::renderer::element::Kind;
    use smithay::utils::{Physical, Point};

    let Some(p) = state.remote_desktop_panel.as_ref() else { return };
    if p.output != output {
        return;
    }
    let scale = output_scale as f32;
    let to_phys = |x: f32, y: f32| {
        Point::<f64, Physical>::from((((x - off_x as f32) * scale) as f64, ((y - off_y as f32) * scale) as f64))
    };

    // Push order matters: this element list is top-first (earliest push =
    // frontmost), so the overlays (status, close button) must be pushed
    // *before* the video frame to end up drawn on top of it — pushing them
    // after, like an earlier version of this function did, buried them
    // completely under the full-screen video (the same class of bug
    // `uzakel`'s QR panel hit for the same reason — see that project's
    // ARCHITECTURE.md §6).

    // Status text floats over the video's bottom-left corner rather than
    // reserving a strip below it — `video_rect` is the full output now, so
    // there is no "below" on-screen to put it in. A small backing card
    // keeps it legible over arbitrary (possibly light) remote content.
    if let Some((buf, sw, sh)) = &p.status_label {
        let m = 16.0;
        let card = Rect::new(p.video_rect.x + m - 8.0, p.video_rect.y + p.video_rect.h - m - *sh as f32 - 8.0, *sw as f32 + 16.0, *sh as f32 + 16.0);
        let phys = to_phys(card.x + 8.0, card.y + 8.0);
        if let Ok(el) = MemoryRenderBufferRenderElement::from_buffer(renderer, phys, buf, Some(1.0), None, None, Kind::Unspecified) {
            out.push(crate::render::BacakElements::Memory(el));
        }
        crate::render::cc_card(out, renderer, card, smithay::backend::renderer::Color32F::new(0.03, 0.05, 0.08, 0.85), 10.0, output_scale, off_x, off_y);
    }

    // PIN card: centered near the top, large and impossible to miss — this
    // is the one piece of information the operator at the shared PC needs
    // to type in, so it stays up until the session actually connects (no
    // point cluttering the screen with it once pairing succeeded).
    if !matches!(p.session.status, SessionStatus::Connected { .. }) {
        if let Some((buf, sw, sh)) = &p.pin_label {
            let m = 16.0;
            let card = Rect::new(p.video_rect.x + (p.video_rect.w - *sw as f32) / 2.0 - 24.0, p.video_rect.y + m, *sw as f32 + 48.0, *sh as f32 + 32.0);
            let phys = to_phys(card.x + 24.0, card.y + 16.0);
            if let Ok(el) = MemoryRenderBufferRenderElement::from_buffer(renderer, phys, buf, Some(1.0), None, None, Kind::Unspecified) {
                out.push(crate::render::BacakElements::Memory(el));
            }
            crate::render::cc_card(out, renderer, card, smithay::backend::renderer::Color32F::new(0.03, 0.05, 0.08, 0.9), 14.0, output_scale, off_x, off_y);
        }
    }

    // Close button: a small pill in the top-right corner, also floating
    // over the video.
    let cx = p.close_rect.x + (p.close_rect.w - p.close_label.as_ref().map(|(_, w, _)| *w as f32).unwrap_or(0.0)) / 2.0;
    let cy = p.close_rect.y + (p.close_rect.h - p.close_label.as_ref().map(|(_, _, h)| *h as f32).unwrap_or(0.0)) / 2.0;
    if let Some((buf, _, _)) = &p.close_label {
        let phys = to_phys(cx, cy);
        if let Ok(el) = MemoryRenderBufferRenderElement::from_buffer(renderer, phys, buf, Some(1.0), None, None, Kind::Unspecified) {
            out.push(crate::render::BacakElements::Memory(el));
        }
    }
    crate::render::cc_card(out, renderer, p.close_rect, smithay::backend::renderer::Color32F::new(0.03, 0.05, 0.08, 0.85), 10.0, output_scale, off_x, off_y);

    if let Some((buf, w, h)) = &p.frame {
        let phys = to_phys(p.video_rect.x, p.video_rect.y);
        // Scale the source frame to fill `video_rect` exactly, regardless of
        // its native resolution — `dst` overrides the element's on-screen
        // logical size the same way `arrow_cursor_element` overrides the
        // cursor's. `src` must be given explicitly too: `from_buffer`
        // defaults a missing `src` to a rect *the same size as `dst`*, not
        // to the buffer's actual native size (see its doc/source) — with
        // only `dst` overridden, that silently sampled a `dst`-sized region
        // starting at the buffer's origin instead of stretching the whole
        // native frame into it. Whenever the remote screen's native
        // resolution differs from this output's (the normal case), that
        // left the real image pinned at native size in the top-left corner
        // and the rest of `video_rect` showing a clamped repeat of its
        // rightmost/bottommost pixel column/row — content that isn't really
        // there, so a tap anywhere past the native size landed nowhere
        // near what was actually visible there on the remote screen. `src`
        // spanning the buffer's true (w, h) makes the GL sampler stretch
        // the *whole* native frame across `dst`, matching what
        // `norm_in_rect` below already assumes when it maps a tap in
        // `video_rect` straight to a 0.0..=1.0 fraction of the remote
        // screen.
        let dst = smithay::utils::Size::<i32, smithay::utils::Logical>::from((p.video_rect.w as i32, p.video_rect.h as i32));
        let src = smithay::utils::Rectangle::<f64, smithay::utils::Logical>::from_size(
            smithay::utils::Size::<f64, smithay::utils::Logical>::from((*w as f64, *h as f64)),
        );
        match MemoryRenderBufferRenderElement::from_buffer(renderer, phys, buf, Some(1.0), Some(src), Some(dst), Kind::Unspecified) {
            Ok(el) => out.push(crate::render::BacakElements::Memory(el)),
            Err(e) => tracing::warn!("remote desktop: failed to upload decoded frame to GPU: {e:?}"),
        }
    }

    // Backdrop, full-bleed — pushed last (this element list is top-first:
    // earliest push = frontmost), so it only ever shows through where the
    // video/labels above don't cover. It's the only visible content while
    // `p.frame` is still `None` (pairing in progress, or a failed
    // connection), so the panel never looks like nothing happened.
    crate::render::cc_card(out, renderer, p.video_rect, smithay::backend::renderer::Color32F::new(0.03, 0.05, 0.08, 0.97), 0.0, output_scale, off_x, off_y);
}

#[cfg(test)]
mod touch_tests {
    //! Headless proof that a touch sequence on the panel routes through the
    //! plugin registry to the same press/motion/release logic the (already
    //! working) pointer path uses, and that the drag's slot is tracked
    //! correctly — this is what real-hardware touch reports couldn't
    //! confirm or deny on their own, since the panel's own network status
    //! is independent of whether the *input* reached it at all.
    use super::*;
    use smithay::reexports::wayland_server::Display;

    fn test_state() -> BacakState {
        let display: Display<BacakState> = Display::new().unwrap();
        BacakState::new(&display, "remote-desktop-touch-test-seat")
    }

    #[test]
    fn touch_down_motion_up_routes_to_remote_desktop_panel() {
        let mut state = test_state();
        let out = state.wm.primary_output().unwrap();
        state.open_remote_desktop_panel(out);
        assert!(state.remote_desktop_panel.is_some());

        let bounds = state.wm.output(out).unwrap().bounds;
        let (x0, y0) = (bounds.x + bounds.w * 0.5, bounds.y + bounds.h * 0.5);

        // Down: the plugin registry must dispatch to "remote_desktop" and
        // claim the slot for this drag.
        let id = crate::plugins::touch_press(&mut state, x0, y0, 7);
        assert_eq!(id, Some("remote_desktop"));
        assert_eq!(state.remote_desktop_touch_slot(), Some(7));

        // Motion on an unrelated slot (a second, unrelated finger) must NOT
        // be consumed — proves the panel isn't blindly claiming every touch.
        let stray = crate::plugins::touch_motion(&mut state, x0 + 10.0, y0, 99);
        assert!(!stray);

        // Motion on the owning slot continues the drag.
        let moved = crate::plugins::touch_motion(&mut state, x0 + 40.0, y0 + 20.0, 7);
        assert!(moved);

        // Up on an unrelated slot must not settle this drag.
        assert!(!crate::plugins::touch_up(&mut state, 99));
        assert_eq!(state.remote_desktop_touch_slot(), Some(7));

        // Up on the owning slot settles it and clears the claim.
        assert!(crate::plugins::touch_up(&mut state, 7));
        assert_eq!(state.remote_desktop_touch_slot(), None);
    }

    #[test]
    fn mouse_and_touch_share_the_same_absolute_path_and_cannot_fight_over_it() {
        let mut state = test_state();
        let out = state.wm.primary_output().unwrap();
        state.open_remote_desktop_panel(out);
        let bounds = state.wm.output(out).unwrap().bounds;
        let (x0, y0) = (bounds.x + bounds.w * 0.25, bounds.y + bounds.h * 0.25);

        // A mouse press claims MOUSE_SLOT, same machinery as touch.
        assert!(crate::plugins::pointer_press(&mut state, x0 as f64, y0 as f64).is_some());
        assert_eq!(state.remote_desktop_touch_slot(), Some(MOUSE_SLOT));

        // A finger landing mid-mouse-drag must not steal the panel's single
        // active drag from the mouse — the press is swallowed (still
        // dispatched to the plugin) but ownership stays with the mouse.
        let extra = crate::plugins::touch_press(&mut state, x0, y0, 3);
        assert_eq!(extra, Some("remote_desktop"));
        assert_eq!(state.remote_desktop_touch_slot(), Some(MOUSE_SLOT));

        // The stray finger's motion/up (slot 3) are correctly ignored — they
        // never owned the drag.
        assert!(!crate::plugins::touch_motion(&mut state, x0 + 5.0, y0, 3));
        assert!(!crate::plugins::touch_up(&mut state, 3));
        assert_eq!(state.remote_desktop_touch_slot(), Some(MOUSE_SLOT));

        // The mouse's own release settles cleanly.
        assert!(crate::plugins::pointer_release(&mut state, x0 as f64, y0 as f64));
        assert_eq!(state.remote_desktop_touch_slot(), None);
    }
}
