[Icon Theme]
Name=BacakOS
Comment=BacakOS özgün, çok renkli düz (flat) ikon seti
Inherits=hicolor
Directories=scalable/apps,scalable/mimetypes,scalable/places,scalable/actions,scalable/status

[scalable/apps]
Size=48
MinSize=16
MaxSize=512
Type=Scalable
Context=Applications

[scalable/mimetypes]
Size=48
MinSize=16
MaxSize=512
Type=Scalable
Context=MimeTypes

[scalable/places]
Size=48
MinSize=16
MaxSize=512
Type=Scalable
Context=Places

[scalable/actions]
Size=48
MinSize=16
MaxSize=512
Type=Scalable
Context=Actions

[scalable/status]
Size=48
MinSize=16
MaxSize=512
Type=Scalable
Context=Status
